etnaviv: Implement primitive restart
etnaviv/mesa pull request #3
Opened 2016-11-11 15:42 UTC by laanwj

Primitive restart is supported on Vivante hardware with the HALTI0 feature (gc860, gc2000, gc3000).

To support draw_info-dependent state changes, add a function etna_update_state_for_draw that updates the index buffer state according to the draw state.

This is one small step on the way to ES3. As there is no ES2 extension for primitive restart, to test this you currently need to force the GL ES version to 3 with `export MESA_GLES_VERSION_OVERRIDE=3.0`.

2016-11-12 16:20 UTC, austriancoder requested changes

2016-11-12 16:20 UTC, austriancoder commented on src/gallium/drivers/etnaviv/etnaviv_context.c
> +      uint32_t new_control = ctx->index_buffer.FE_INDEX_STREAM_CONTROL;
Add a blank line before if start.

2016-11-12 16:20 UTC, austriancoder commented on src/gallium/drivers/etnaviv/etnaviv_context.c
> +      if (info->primitive_restart) {
Brackets not needed.

2016-11-12 16:20 UTC, austriancoder commented on src/gallium/drivers/etnaviv/etnaviv_context.c
> +      if (ctx->index_buffer.FE_INDEX_STREAM_CONTROL != new_control ||
Add blank line before if.

2016-11-12 16:20 UTC, austriancoder commented on src/gallium/drivers/etnaviv/hw/isa.xml.h
> +#define INST_TYPE_F32						0x00000000
Maybe split up the commit in two patches:
1) "etnaviv: update generated header files"
2) "etnaviv: Implement primitive restart"

2016-11-14 08:13 UTC, laanwj commented
Ok added newlines, removed braces and removed the updating of .xml.h as you already did so.

2016-11-14 09:09 UTC, merged

2016-11-14 09:09 UTC, austriancoder commented
Thanks